// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RpsPolicyApp.DbContext;
using System;

namespace RpsPolicyApp.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    partial class PolicyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RpsPolicyApp.Models.Policy", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("PolicyEffectiveDate");

                    b.Property<DateTime>("PolicyExpirationDate");

                    b.Property<int>("PolicyNumber");

                    b.Property<string>("PrimaryInsuredMailingAddress");

                    b.Property<string>("PrimaryInsuredName");

                    b.Property<string>("PrimaryInsuredState");

                    b.Property<string>("PrimaryInsuredZipCode");

                    b.Property<string>("PrimaryInusredCity");

                    b.Property<string>("RiskAddress");

                    b.Property<string>("RiskCity");

                    b.Property<int>("RiskConstruction");

                    b.Property<string>("RiskState");

                    b.Property<int>("RiskYearBuilt");

                    b.Property<string>("RiskZipCode");

                    b.HasKey("id");

                    b.ToTable("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
